[project]
name = "alex-swapper"
authors = []
description = ""
telemetry = false
requirements = []

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"
depends_on = []

[contracts.sip010-token]
path = "contracts/sip010-token.clar"
depends_on = ["sip010-ft-trait"]

[contracts.swap-helper-trait]
path = "contracts/swap-helper-trait.clar"
depends_on = ["sip010-ft-trait"]

[contracts.swap-helper]
path = "contracts/swap-helper.clar"
depends_on = ["swap-helper-trait", "sip010-ft-trait"]

[contracts.alex-swapper]
path = "contracts/alex-swapper.clar"
depends_on = ["sip010-ft-trait", "swap-helper-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
